# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
# see http://docs.travis-ci.com/user/encryption-keys
env:
  # codacy stuff
  - secure: "bs5UYzuaxgXfRlgNMy3lyFoE4MxccR8GcZqlHncC2uFsH24tWKqB0RuHisxk0KRhB/zmISgCf+Ut6PRyXZbSsr62O3EuCDJPlxz3pHOsATC5I1jzn01ABwJa1XK41fLY8hj3MEdXaOjVywqWkn/jmgCTNbc8ZhLeWbhDX5GdUGI="
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile clean coverage test coverageReport coverageAggregate codacyCoverage
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dd3b25f5e3048e4187b8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false
# Use container-based infrastructure
sudo: false
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
